on: [push]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: logseq/publish-spa@v0.3.1
        with:
          graph-directory: .
          output-directory: www
          version: 0.10.6
          theme-mode: logseq
          accent-color: blue
      - name: Add .nojekyll file
        run: touch www/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www